server:
  port: ${PORT:8085}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  catalog:
    name: catalogQueue
