spring:
#   security:
#     oauth2:
#       client:
#         provider:
#           google:
#             issuer-uri: https://accounts.google.com
#         registration:
#           google:
#             client-id: 728533990652-jdps7gpf08vbisa3sjjttrr5423b5n42.apps.googleusercontent.com
#             client-secret: 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
#             scope: openid
#             redirect-uri: http://localhost:8080/login/oauth2/code/google
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
#         - id: accountRoute
#           uri: http://localhost:8080
#           predicates:
#             - Path=/account/**
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: series-service-route
          uri: lb://series-service
          predicates:
            - Path=/series/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
#       default-filters:
#         - LogFilter
#         - TokenRelay
server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
