server:
  port: ${PORT:8082}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  jpa:
    deferDatasourceInitialization: true
    hibernate:
      ddlAuto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/backendparcial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  catalog:
    name: catalogQueue
