server:
  port: ${PORT:8083}
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/series
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  serie:
    name: serieQueue
